name: Test invoke.py pip
on:
  push:
    branches:
      - 'main'
      - 'development'
  pull_request:

concurrency:
   group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
   cancel-in-progress: true

jobs:
  matrix:
    strategy:
      matrix:
        stable-diffusion-model:
          - diffusers-1.5
        requirements-file:
          - requirements-lin-cuda.txt
          - requirements-lin-amd.txt
          - requirements-mac-mps-cpu.txt
          - requirements-win-colab-cuda.txt
        python-version:
          # - '3.9'
          - '3.10'
        include:
          - requirements-file: requirements-lin-cuda.txt
            os: ubuntu-22.04
            github-env: $GITHUB_ENV
          - requirements-file: requirements-lin-amd.txt
            os: ubuntu-22.04
            github-env: $GITHUB_ENV
          - requirements-file: requirements-mac-mps-cpu.txt
            os: macOS-12
            github-env: $GITHUB_ENV
          - requirements-file: requirements-win-colab-cuda.txt
            os: windows-2022
            github-env: $env:GITHUB_ENV
    name: ${{ matrix.requirements-file }} on ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    env:
      INVOKEAI_ROOT: '${{ github.workspace }}/invokeai'
      PYTHONUNBUFFERED: 1
      HAVE_SECRETS: ${{ secrets.HUGGINGFACE_TOKEN != '' }}
    steps:
      - name: Checkout sources
        id: checkout-sources
        uses: actions/checkout@v3

      - name: set INVOKEAI_ROOT Windows
        if: matrix.os == 'windows-2022'
        run: |
          echo "INVOKEAI_ROOT=${{ github.workspace }}\invokeai" >> ${{ matrix.github-env }}
          echo "INVOKEAI_OUTDIR=${{ github.workspace }}\invokeai\outputs" >> ${{ matrix.github-env }}

      - name: set INVOKEAI_ROOT others
        if: matrix.os != 'windows-2022'
        run: |
          echo "INVOKEAI_ROOT=${{ github.workspace }}/invokeai" >> ${{ matrix.github-env }}
          echo "INVOKEAI_OUTDIR=${{ github.workspace }}/invokeai/outputs" >> ${{ matrix.github-env }}

      - name: create models.yaml from example
        run: |
          mkdir -p ${{ env.INVOKEAI_ROOT }}/configs
          cp configs/models.yaml.example ${{ env.INVOKEAI_ROOT }}/configs/models.yaml

      - name: Use Cached Stable Diffusion Model
        id: cache-sd-model
        uses: actions/cache@v3
        env:
          cache-name: huggingface-${{ matrix.stable-diffusion-model }}
        with:
          path: ~/.cache/huggingface
          key: ${{ env.cache-name }}

      - name: set test prompt to main branch validation
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo "TEST_PROMPTS=tests/preflight_prompts.txt" >> ${{ matrix.github-env }}

      - name: set test prompt to development branch validation
        if: ${{ github.ref == 'refs/heads/development' }}
        run: echo "TEST_PROMPTS=tests/dev_prompts.txt" >> ${{ matrix.github-env }}

      - name: set test prompt to Pull Request validation
        if: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/development' }}
        run: echo "TEST_PROMPTS=tests/validate_pr_prompt.txt" >> ${{ matrix.github-env }}

      - name: create requirements.txt
        run: cp 'environments-and-requirements/${{ matrix.requirements-file }}' '${{ matrix.requirements-file }}'

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          # cache: 'pip'
          # cache-dependency-path: ${{ matrix.requirements-file }}

      - name: install dependencies
        run: pip3 install --upgrade pip setuptools wheel

      - name: install requirements
        run: pip3 install -r '${{ matrix.requirements-file }}'

      - name: run configure_invokeai.py
        id: run-preload-models
        run: |
          if [ "${HAVE_SECRETS}" == true ] ; then
            mkdir -p ~/.huggingface
            echo -n '${{ secrets.HUGGINGFACE_TOKEN }}' > ~/.huggingface/token
          fi
          python3 scripts/configure_invokeai.py \
              --no-interactive --yes \
              --full-precision  # can't use fp16 weights without a GPU

      - name: Run the tests
        id: run-tests
        if: matrix.os != 'windows-2022'
        env:
          # Set offline mode to make sure configure preloaded successfully.
          HF_HUB_OFFLINE: 1
          HF_DATASETS_OFFLINE: 1
          TRANSFORMERS_OFFLINE: 1
        run: |
          time python3 scripts/invoke.py \
            --no-patchmatch \
            --no-nsfw_checker \
            --model ${{ matrix.stable-diffusion-model }} \
            --from_file ${{ env.TEST_PROMPTS }} \
            --root="${{ env.INVOKEAI_ROOT }}" \
            --outdir="${{ env.INVOKEAI_OUTDIR }}"

      - name: Archive results
        id: archive-results
        if: matrix.os != 'windows-2022'
        uses: actions/upload-artifact@v3
        with:
          name: results_${{ matrix.requirements-file }}_${{ matrix.python-version }}
          path: ${{ env.INVOKEAI_ROOT }}/outputs
